### ISSUE TITLE
Internal server error using apoa1

### ISSUE THREAD

**Issue by ljmartin** [pandegroup/openmm-setup#11]
Hi,
I have just installed openmm-setup and it works fine for setting up a gromacs simulation (using a pdb file, not gro file). 

I have the following error when running openmm-setup using PDB as input, forcefield as CHARMM36, any of the water models, and the apoa1.pdb available on http://www.ks.uiuc.edu/Research/namd/utilities/ (as well as some other pdbs I use in gromacs or NAMD):

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">`
`<title>500 Internal Server Error</title>`
`<h1>Internal Server Error</h1>`
`<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>`

Not sure if Im doing it wrong or if theres an error. Error is reproduced on MacOS running safari, or on Linux mint running firefox. No private browsing was turned on.

Cheers

PS:
this pops up in the terminal when the error occurs:
``` 
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Mar/2018 15:00:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Mar/2018 15:00:19] "GET /selectFiles?type=pdb HTTP/1.1" 200 -
127.0.0.1 - - [06/Mar/2018 15:01:08] "POST /configureFiles HTTP/1.1" 200 -
[2018-03-06 15:01:09,009] ERROR in app: Exception on /setSimulationOptions [POST]
Traceback (most recent call last):
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/openmmsetup/openmmsetup.py", line 304, in setSimulationOptions
    return createScript()
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/openmmsetup/openmmsetup.py", line 468, in createScript
    pdbType = session['pdbType']
  File "/home/lewis/anaconda2/lib/python2.7/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'pdbType'
127.0.0.1 - - [06/Mar/2018 15:30:53] "POST /setSimulationOptions HTTP/1.1" 500 -
```

**Comment by ljmartin** [comment]
I have since installed openmm and openmm-setup with miniconda3 (as was recommended in the documentation) and the above errors don't occur.

**Comment by peastman** [comment]
Possibly this is something that's incompatible with Python 2?  I should look into that.  OpenMM itself gets tested pretty thoroughly with Python 2.7, but OpenMM-Setup has mainly been tested on 3.x versions.
